### ISSUE TITLE
Any chance to update deps on this project?

### ISSUE THREAD

**Issue by kevinthecity** [RevelationOnline/skillplanner#9]
Tried getting this project running on my box for a friend, but ran into a handful of issues. I got most of the way there, however running into this bug now:

![screen shot 2019-01-31 at 9 42 12 pm](https://user-images.githubusercontent.com/1014106/52099430-3e7f4000-25a1-11e9-8259-5ec846f4418e.png)

I tried different variations of installing compass, but still getting the error. It could be related to this issue, but I'm not super well versed in some of these specific technologies so I can't say for sure after spending about ~15 minutes on this.

https://github.com/yeoman/generator-angular/issues/1172

Any help / guidance appreciated, thanks!

Also, here's the list of commands I ran, in order  (with various grunt / grunt serves sprinkled in). Maybe that gives some insight as well.

```
git clone git@github.com:RevelationOnline/skillplanner.git
brew install grunt
npm install grunt --save-dev
npm install load-grunt-tasks
npm install time-grunt
npm install
grunt install
brew install bower
bower install
npm install -g compass
npm install karma grunt-karma karma-phantomjs-launcher karma-jasmine
npm install grunt-contrib-compass --save-dev
npm install -g sass
```

**Comment by Sphazz** [comment]
It's been ages since I've had to debug this project, nor do I remember how it works, so grain of salt with my comments.

`gem install compass`
https://github.com/gruntjs/grunt-contrib-watch/issues/294#issuecomment-420548337

That's a completely empty suggestion though, I'm going off of nothing more than a Google search. 

I pulled out my old copy and didn't have any issues (W10), but again, I have everything already set up, including compass.

I updated my fork: https://github.com/Sphazz/skillplanner
But that shouldn't solve your problem.

A lot of the dependencies for this project are either deprecated, or so far out of date they are completely incompatible with their most recently updated versions. So updating dependencies would probably cause more harm then good.

This type of project needs to be re-imagined with React or Angular 7. Things have come a long way since this was originally conceived. The conversion script could be very easily reused through.

**Comment by kevinthecity** [comment]
O wow  - that did actually work! 🙌 Thanks for putting in the time to look at this. Really appreciate it. 🙏 Have a great week!

**Comment by andir** [comment]
I do not currently have intentions to keep this updated. If someone wants to file a PR to update the repo to a working state I'll happily merge it.

**Comment by kevinthecity** [comment]
Sounds good - thanks for the help! Will close this issue.
